ProjectStructure.Presentation.MVC_Day1/Models/ErrorViewModel.cs
namespace ProjectStructure.MVC_Day1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ProjectStructure.Presentation.MVC_Day1/Areas/NashTech/Controllers/RookieController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectStructure.Domain;
using ProjectStructure.Domain.Enums;
using ProjectStructure.Domain.Models;
using ProjectStucture.Application.Services.Interfaces;

namespace ProjectStructure.MVC_Day1.Areas.NashTech.Controllers
{
    [Area("NashTech")]
    public class RookieController : Controller
    {
        private readonly IRookieService _rookieService;
        private readonly IExcelService _excelService;

        public RookieController(IRookieService rookieService, IExcelService excelService)
        {
            _rookieService = rookieService;
            _excelService = excelService;
        }

        public IActionResult Index(int page = 1, int pageSize = 2)
        {
            var people = _rookieService.GetPeople()
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToList();
            ViewBag.CurrentPage = page;
            ViewBag.PageSize = pageSize;
            ViewBag.TotalPages = Math.Ceiling((double)_rookieService.GetPeople().Count() / pageSize);

            return View(people);
        }

        public IActionResult PeopleByGender(string gender, bool firstLoad)
        {
            if (!string.IsNullOrEmpty(gender) && Enum.IsDefined(typeof(GenderType), gender))
            {
                var people = _rookieService.GetPeopleByGender(gender);
                if (firstLoad)
                    return View(people);
                if (people.Count == 0)
                {
                    ViewBag.Error = "No person found";
                    return PartialView("_TablePeople", new List<Person>());
                }
                return PartialView("_TablePeople", people);
            }
            ViewBag.Error = "Gender is not valid";
            return PartialView("_TablePeople", new List<Person>());
        }

        public IActionResult TheOldestPerson()
        {
            var person = _rookieService.GetOldestPerson();
            if (person == null)
            {
                return RedirectToAction("Detail");
            }
            return RedirectToAction("Detail", new { id = person.Id });
        }

        public IActionResult PeopleWithFullName()
        {
            var people = _rookieService.GetPeople().Select(p => new
            {
                Id = p.Id,
                FullName = p.FirstName + " " + p.LastName,
                Gender = p.Gender,
                DateOfBirth = p.DateOfBirth,
                PhoneNumber = p.PhoneNumber,
                BirthPlace = p.BirthPlace,
                IsGraduated = p.IsGraduated
            });
            if (people.Count() == 0)
            {
                ViewBag.IsNoElement = "No person found";
                return View();
            }
            return View(people);
        }

        public IActionResult PeopleByYearOfBirth(string ope, string year, bool firstLoad)
        {
            if (!string.IsNullOrEmpty(ope) && Enum.IsDefined(typeof(ComparisionOperator), ope) && int.TryParse(year, out var value))
            {
                var people = _rookieService.FilterByBirthYear(value, ope);
                ViewBag.Year = year;
                if (firstLoad)
                    return View(people);

                if (people.Count == 0)
                {
                    ViewBag.IsNoElement = "No person found";
                    return PartialView("_TablePeople", new List<Person>());
                }
                return PartialView("_TablePeople", people);
            }
            ViewBag.Error = "Invalid input";
            return PartialView("_TablePeople", new List<Person>());
        }

        public IActionResult ExportToExcel()
        {
            var people = _rookieService.GetPeople();
            var file = _excelService.ExportToExcel(people);
            return File(file, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "people.xlsx");
        }

        public IActionResult Add()
        {
            //using enum GenderType to add to select tag
            ViewBag.GenderTypes = new SelectList(Enum.GetValues(typeof(GenderType)));
            return View(new Person());
        }

        [HttpPost]
        public IActionResult Add(Person person)
        {
            ViewBag.GenderTypes = new SelectList(Enum.GetValues(typeof(GenderType)));
            if (ModelState.IsValid)
            {
                Person personReturned = _rookieService.AddPerson(person);
                if (personReturned != null)
                {
                    //I want to Index has a message success
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Message = "Add failed";
                    return View(person);
                }
            }
            return View(person);
        }

        public IActionResult Detail(Guid id)
        {
            var person = _rookieService.GetPersonById(id);
            if (person == null)
            {
                ViewBag.Error = "Person not found";
                return View();
            }
            ViewBag.GenderTypes = Enum.GetValues(typeof(GenderType));
            return View(person);
        }

        [HttpGet]
        public IActionResult Edit(Guid id)
        {
            var person = _rookieService.GetPersonById(id);
            if (person == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.GenderTypes = Enum.GetValues(typeof(GenderType));
            return View(person);
        }

        [HttpPost]
        public IActionResult Edit(Person person)
        {
            ViewBag.GenderTypes = Enum.GetValues(typeof(GenderType));
            if (ModelState.IsValid)
            {
                Person personReturned = _rookieService.UpdatePerson(person);
                if (personReturned != null)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Message = "Update failed";
                    return RedirectToAction("Edit", person.Id);
                }
            }
            return View(person);
        }

        [HttpDelete]
        public IActionResult Delete(Guid id)
        {
            var result = _rookieService.DeletePerson(id);
            if (result != null)
            {
                return Json(new { success = true });
            }
            else
            {
                return Json(new { success = false });
            }
        }
    }
}

ProjectStructure.Presentation.MVC_Day1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectStructure.MVC_Day1.Models;
using System.Diagnostics;

namespace ProjectStructure.MVC_Day1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ProjectStructure.Presentation.MVC_Day1/Areas/NashTech/Views/Rookie/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model ProjectStructure.Domain.Models.Person

<form asp-area="NashTech" asp-action="Add" asp-controller="Rookie" method="post">
    <div class="form-group">
        <label asp-for="FirstName">First Name</label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName">Last Name</label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="DateOfBirth">Date of Birth</label>
        <input asp-for="DateOfBirth" class="form-control" type="date" />
        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PhoneNumber">Phone Number</label>
        <input asp-for="PhoneNumber" class="form-control" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="BirthPlace">Birth Place</label>
        <input asp-for="BirthPlace" class="form-control" />
        <span asp-validation-for="BirthPlace" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="IsGraduated">Is Graduated?</label>
        <select asp-for="IsGraduated" class="form-control" asp-items="@(new SelectList(Model.GraduatedOption, "Key", "Description"))">
        </select>
    </div>

    <div class="form-group">
        <label asp-for="Gender">Gender</label>
        <select asp-for="Gender" asp-items="@(new SelectList(Model.GenderOption, "Key", "Description"))" class="form-control">
            <option>Please select gender</option>
        </select>
        <span asp-validation-for="Gender" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Add Person</button>
</form>

ProjectStructure.Presentation.MVC_Day1/Areas/NashTech/Views/Rookie/Detail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model ProjectStructure.Domain.Models.Person

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Person Details</h2>
@if (ViewBag.Error != null)
{
    <h3 class="text-danger">@ViewBag.Error</h3>
}
else
{
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label for="FirstName">First Name:</label>
                <input id="FirstName" type="text" class="form-control" value="@Model.FirstName" readonly />
            </div>
            <div class="form-group">
                <label for="LastName">Last Name:</label>
                <input id="LastName" type="text" class="form-control" value="@Model.LastName" readonly />
            </div>
            <div class="form-group">
                <label for="DateOfBirth">Date of Birth:</label>
                <input id="DateOfBirth" type="text" class="form-control" value="@Model.DateOfBirth.ToShortDateString()" readonly />
            </div>
            <div class="form-group">
                <label for="PhoneNumber">Phone Number:</label>
                <input id="PhoneNumber" type="text" class="form-control" value="@Model.PhoneNumber" readonly />
            </div>
            <div class="form-group">
                <label for="BirthPlace">Birth Place:</label>
                <input id="BirthPlace" type="text" class="form-control" value="@Model.BirthPlace" readonly />
            </div>
            <div class="form-group">
                <label for="IsGraduated">Is Graduated:</label>
                <input id="IsGraduated" type="text" class="form-control" value="@(Model.IsGraduated==true ? "Yes" : "No")" readonly />
            </div>
            <div class="form-group">
                <label for="Gender">Gender:</label>
                <input id="Gender" type="text" class="form-control" value="@Model.Gender" readonly />
            </div>
            <button id="deleteBtn" onclick="deletePerson('@Model.Id')" class="btn btn-danger">Delete</button>
        </div>
    </div>
}


@section Scripts {
    <script>
        function deletePerson(id) {
            var confirmDelete = confirm("Are you sure you want to delete this person?");
            if (confirmDelete) {
                $.ajax({
                    url: '/NashTech/Rookie/Delete',
                    type: 'DELETE',
                    data: { id: id },
                    success: function (response) {
                        if (response.success) {
                            window.location.href = '/NashTech/Rookie/Index';
                        } else {
                            alert('Delete failed');
                        }
                    }
                });
            }
        }
    </script>
}

ProjectStructure.Presentation.MVC_Day1/Areas/NashTech/Views/Rookie/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model ProjectStructure.Domain.Models.Person

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Person</h2>

<form asp-area="NashTech" asp-action="Edit" asp-controller="Rookie" method="post">
    <input type="hidden" asp-for="Id"/>
    <div class="form-group">
        <label asp-for="FirstName">First Name</label>
        <input asp-for="FirstName" class="form-control" value="@Model.FirstName" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName">Last Name</label>
        <input asp-for="LastName" class="form-control" value="@Model.LastName" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="IsGraduated">Is Graduated?</label>
        <select asp-for="IsGraduated" class="form-control">
            <option value="true" >Yes</option>
            <option value="false" >No</option>
        </select>
    </div>

    <div class="form-group">
        <label asp-for="DateOfBirth">Date of Birth</label>
        <input asp-for="DateOfBirth" class="form-control" type="date" value="@Model.DateOfBirth.ToString("yyyy-MM-dd")" />
        <span asp-validation-for="DateOfBirth" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PhoneNumber">Phone Number</label>
        <input asp-for="PhoneNumber" class="form-control" value="@Model.PhoneNumber" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="BirthPlace">Birth Place</label>
        <input asp-for="BirthPlace" class="form-control" value="@Model.BirthPlace" />
        <span asp-validation-for="BirthPlace" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label for="Gender">Gender:</label>
        <select id="Gender" class="form-control" asp-for="Gender" asp-items="@(new SelectList(Model.GenderOption, "Key", "Description"))">
        </select>
    </div>

    <div class="form-group">
        <label for="IsGraduated">Is Graduated:</label>
        <select id="IsGraduated" class="form-control" asp-for="IsGraduated" asp-items="@(new SelectList(Model.GraduatedOption, "Key", "Description"))">
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Save Change</button>
</form>

ProjectStructure.Presentation.MVC_Day1/Areas/NashTech/Views/Rookie/Index.cshtml
@model IEnumerable<ProjectStructure.Domain.Models.Person>
@{
    var prevDisabled = ViewBag.CurrentPage == 1 ? "disabled" : "";
    var nextDisabled = ViewBag.CurrentPage >= ViewBag.TotalPages ? "disabled" : "";
    var startPage = Math.Max(1, ViewBag.CurrentPage - 2);
    var endPage = Math.Min(ViewBag.TotalPages, ViewBag.CurrentPage + 2);
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List all people</h1>

@Html.Partial("_TablePeople", Model)
<nav>
    <ul class="pagination">
        <li class="page-item @prevDisabled">
            <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.CurrentPage - 1, pageSize = ViewBag.PageSize })">Prev</a>
        </li>
        @if (startPage > 1)
        {
            <li class="page-item">
                <a class="page-link" href="@Url.Action("Index", new { page = 1, pageSize = ViewBag.PageSize })">1</a>
            </li>
            <li class="page-item disabled">
                <span class="page-link">...</span>
            </li>
        }
        @for (var i = startPage; i <= endPage; i++)
        {
            var active = i == ViewBag.CurrentPage ? "active" : "";
            <li class="page-item @active">
                <a class="page-link" href="@Url.Action("Index", new { page = i, pageSize = ViewBag.PageSize })">@i</a>
            </li>
        }
        @if (endPage < ViewBag.TotalPages)
        {
            <li class="page-item disabled">
                <span class="page-link">...</span>
            </li>
            <li class="page-item">
                <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.TotalPages, pageSize = ViewBag.PageSize })">@ViewBag.TotalPages</a>
            </li>
        }
        <li class="page-item @nextDisabled">
            <a class="page-link" href="@Url.Action("Index", new { page = ViewBag.CurrentPage + 1, pageSize = ViewBag.PageSize })">Next</a>
        </li>
    </ul>
</nav>

<br/>
<br/>
<a asp-area="NashTech" asp-controller="Rookie" asp-action="ExportToExcel" class="btn btn-primary">Export to Excel</a>

ProjectStructure.Presentation.MVC_Day1/Areas/NashTech/Views/Rookie/PeopleByGender.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<ProjectStructure.Domain.Models.Person>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<label for="male">Male</label>
<input id="male" checked type="radio" name="gender" value="male" />
<br />
<label for="female">Female</label>
<input id="female" type="radio" name="gender" value="female" />
<br />
<label for="unknown">Unknown</label>
<input id="unknown" type="radio" name="gender" value="unknown" />
<br />
<label for="other">Other</label>
<input id="other" type="radio" name="gender" value="other" />
<br />

@if (ViewBag.IsNoElement != null)
{
    <h3 class="text-danger">@ViewBag.IsNoElement</h3>
}
else
{
    <div id="peopleTable">
        @Html.Partial("_TablePeople", Model)
    </div>
}

@section Scripts {
    <script>
        $(document).ready(function () {
            $('input[type=radio][name=gender]').change(function () {
                $.ajax({
                    url: '/NashTech/Rookie/PeopleByGender',
                    type: 'GET',
                    data: { gender: $(this).val(), firstLoad: false },
                    success: function (response) {
                        $('#peopleTable').html(response);
                    }
                });
            });
        });
    </script>
}

ProjectStructure.Presentation.MVC_Day1/Areas/NashTech/Views/Rookie/PeopleByYearOfBirth.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model IEnumerable<ProjectStructure.Domain.Models.Person>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<label for="eq">Equal</label>
<input id="eq" checked type="radio" name="ope" value="eq" />
<br />
<label for="gt">Greater than</label>
<input id="gt"  type="radio" name="ope" value="gt" />
<br />
<label for="lt">Less than</label>
<input id="lt" type="radio" name="ope" value="lt" />
<br />

<input type="number" id="year" required value="@ViewBag.Year" />

@if (ViewBag.IsNoElement != null)
{
    <h3 class="text-danger">@ViewBag.IsNoElement</h3>
}
else
{
    <div id="peopleTable">
        @Html.Partial("_TablePeople", Model)
    </div>
}

@section Scripts {
    <script>
        $(document).ready(function () {
            $('input[type=radio][name=ope], #year').change(function () {
                var ope = $('input[type=radio][name=ope]:checked').val();
                var year = $('#year').val();
                $.ajax({
                    url: '/NashTech/Rookie/PeopleByYearOfBirth',
                    type: 'GET',
                    data: { ope: ope, year: year, firstLoad: false },
                    success: function (response) {
                        $('#peopleTable').html(response);
                    }
                });
            });
        });
    </script>
}

ProjectStructure.Presentation.MVC_Day1/Areas/NashTech/Views/Rookie/PeopleWithFullName.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List people combined name</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                FullName
            </th>
            <th>
                Gender
            </th>
            <th>
                DateOfBirth
            </th>
            <th>
                PhoneNumber
            </th>
            <th>
                BirthPlace
            </th>
            <th>
                IsGraduated
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class=@(item.IsGraduated ? "text-success" : "text-danger")>
                <td>
                    @item.FullName
                </td>
                <td>
                    @item.Gender
                </td>
                <td>
                    @item.DateOfBirth
                </td>
                <td>
                    @item.PhoneNumber
                </td>
                <td>
                    @item.BirthPlace
                </td>
                <td>
                    @(item.IsGraduated ? "Yes" : "No")
                </td>
            </tr>
        }
    </tbody>
</table>

ProjectStructure.Presentation.MVC_Day1/Areas/NashTech/Views/Rookie/TheOldestPerson.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@Model ProjectStructure.Domain.Models.Person

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>The oldest person</h1>

<div>
    <h3>First name: @Model.FirstName</h3>
    <h3>Last name: @Model.LastName</h3>
    <h3>Gender: @Model.Gender</h3>
    <h3>Date of birth: @Model.DateOfBirth</h3>
    <h3>Phone number: @Model.PhoneNumber</h3>
    <h3>Birth place: @Model.BirthPlace</h3>
    <h3>Is graduated: @Model.IsGraduated</h3>
</div>

ProjectStructure.Presentation.MVC_Day1/Areas/NashTech/Views/Rookie/_TablePeople.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model IEnumerable<ProjectStructure.Domain.Models.Person>


<a asp-area="NashTech" asp-controller="Rookie" asp-action="Add" class="btn btn-primary">Add new person</a> -
<h3 class="text-success">@ViewBag.Message</h3>
<h3 class="text-danger">@ViewBag.Error</h3>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthPlace)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsGraduated)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class=@(item.IsGraduated ? "text-success" : "text-danger")>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Gender)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BirthPlace)
                </td>
                <td>
                    @(item.IsGraduated ? "Yes" : "No")
                </td>
                <td>
                    <a asp-area="NashTech" asp-controller="Rookie" asp-action="Detail" asp-route-id="@item.Id" class="btn btn-success">Detail</a>
                    <a asp-area="NashTech" asp-controller="Rookie" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Edit</a>
                    <a class="btn btn-danger" onclick="deletePerson('@item.Id')">Delete</a>
                </td>

            </tr>
        }
    </tbody>
</table>


<script>
    function deletePerson(id) {
        var confirmDelete = confirm("Are you sure you want to delete this person?");
        if (confirmDelete) {
            $.ajax({
                url: '/NashTech/Rookie/Delete',
                type: 'DELETE',
                data: { id: id },
                success: function (response) {
                    if (response.success) {
                        // Remove the row from the table
                        $('tr').has('a[onclick="deletePerson(\'' + id + '\')"]').remove();
                    } else {
                        alert('Delete failed');
                    }
                }
            });
        }
    }
</script>

ProjectStructure.Presentation.MVC_Day1/Areas/NashTech/Views/Rookie/_TableView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ProjectStructure.Presentation.MVC_Day1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ProjectStructure.Presentation.MVC_Day1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectStructure.MVC_Day1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectStructure.MVC_Day1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectStructure.MVC_Day1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="NashTech" asp-controller="Rookie" asp-action="Index" >List all people</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-primary" asp-area="NashTech" asp-controller="Rookie" asp-action="PeopleByGender" asp-route-gender="male" asp-route-firstLoad="true">People by gender</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-warning" asp-area="NashTech" asp-controller="Rookie" asp-action="TheOldestPerson">The first oldest person</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-success" asp-area="NashTech" asp-controller="Rookie" asp-action="PeopleWithFullName">List people combined name</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="NashTech" asp-controller="Rookie" asp-action="PeopleByYearOfBirth" asp-route-ope="eq" asp-route-year="2000" asp-route-firstLoad="true">People by year of birth</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProjectStructure.MVC_Day1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>